tasks:
  - name: Setup & Build Java
    command: sdk install java 17.0.9-tem < /dev/null
vscode:
   extensions:
    - "vscjava.vscode-java-pack"
    - "redhat.fabric8-analytics"
    - "redhat.java"
    - "vscjava.vscode-java-debug"
    - "vscjava.vscode-java-test"
    - "vscjava.vscode-java-dependency"
    - "vscjava.vscode-maven"